
feign:
  name: TruProxyAP
  url: https://exercise.trunarrative.cloud/TruProxyAPI/rest/Companies
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
